USE `movie-collection`;

INSERT INTO genres(genre)
VALUES ('ACTION');

INSERT INTO genres(genre)
VALUES ('COMEDY');

INSERT INTO genres(genre)
VALUES ('DRAMA');

INSERT INTO genres(genre)
VALUES ('ANIMATION');

INSERT INTO genres(genre)
VALUES ('ADVENTURE');

INSERT INTO genres(genre)
VALUES ('FANTASY');

INSERT INTO genres(genre)
VALUES ('ROMANCE');

INSERT INTO genres(genre)
VALUES ('THRILLER');

INSERT INTO genres(genre)
VALUES ('CRIME');

INSERT INTO genres(genre)
VALUES ('DOCUMENTARY');

INSERT INTO genres(genre)
VALUES ('SERIAL');

INSERT INTO platforms(platform)
VALUES ('HBO');

INSERT INTO platforms(platform)
VALUES ('DISNEY');

INSERT INTO platforms(platform)
VALUES ('NETFLIX');

INSERT INTO movies(title1, title2, duration, year, imdb_url, trailer_url, poster_url, bulgarian_language, description , rating)
VALUES ('The Avengers',
        null,
        143,
        2012,
        'https://www.imdb.com/title/tt0848228/',
        'https://www.youtube.com/watch?v=eOrNdBpGMv8',
        'https://www.themoviedb.org/t/p/original/tYqp6vEOo8YlVWrYQvt9nyOhsA2.jpg',
        true,
        null,
        8),
       ('Avengers',
        'Age of Ultron',
        141,
        2015,
        'https://www.imdb.com/title/tt2395427/',
        'https://www.youtube.com/watch?v=zw8QYO_BJYY',
        'https://static.posters.cz/image/750/posters/the-avengers-age-of-ultron-one-sheet-i27861.jpg',
        true,
        null,
        9),
       ('Avengers',
        'Infinity War',
        149,
        2018,
        'https://www.imdb.com/title/tt4154756/',
        'https://www.youtube.com/watch?v=t1QDnIjZlk8',
        'https://static.posters.cz/image/1300/posters/avengers-infinity-war-one-sheet-i122134.jpg',
        true,
        null,
        7),
       ('Avengers',
        'Endgame',
        181,
        2019,
        'https://www.imdb.com/title/tt4154796/',
        'https://www.youtube.com/watch?v=pLvovWcmJ-k',
        'https://static.posters.cz/image/1300/posters/avengers-endgame-journey-s-end-i122136.jpg',
        true,
        null,
        9),
       ('The Dark Knight',
        null,
        152,
        2008,
        'https://www.imdb.com/title/tt0468569/',
        'https://www.youtube.com/watch?v=EXeTwQWrcwY',
        'https://images.pristineauction.com/158/1582578/main_1597378492-The-Dark-Knight-27x40-Movie-Poster-PristineAuction.com.jpg',
        true,
        null,
        8),
       ('The Dark Knight Rises',
        null,
        164,
        2012,
        'https://www.imdb.com/title/tt1345836/',
        'https://www.youtube.com/watch?v=GokKUqLcvD8',
        'https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        7),
       ('Batman Begins',
        null,
        140,
        2005,
        'https://www.imdb.com/title/tt0372784/',
        'https://www.youtube.com/watch?v=FiL1_5DWV7Y',
        'https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
        true,
        null,
        8),
       ('The Lord of the Rings',
        'The Fellowship of the Ring',
        178,
        2001,
        'https://www.imdb.com/title/tt0120737/',
        'https://www.youtube.com/watch?v=_e8QGuG50ro',
        'https://m.media-amazon.com/images/I/81EBp0vOZZL._AC_SY741_.jpg',
        false,
        null,
        8.5),
       ('The Lord of the Rings',
        'The Two Towers',
        179,
        2002,
        'https://www.imdb.com/title/tt0167261/',
        'https://www.youtube.com/watch?v=LbfMDwc4azU',
        'https://www.themoviedb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
        false,
        null,
        9.1),
       ('The Lord of the Rings',
        'The Return of the King',
        201,
        2003,
        'https://www.imdb.com/title/tt0167260/',
        'https://www.youtube.com/watch?v=r5X-hFf6Bwo',
        'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
        false,
        null,
        8.7),
       ('The Hobbit',
        'An Unexpected Journey',
        169,
        2012,
        'https://www.imdb.com/title/tt0903624/',
        'https://www.youtube.com/watch?v=SDnYMbYB-nU',
        'https://m.media-amazon.com/images/M/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_FMjpg_UX1000_.jpg',
        false,
        null,
        8.3),
       ('The Hobbit',
        'The Desolation of Smaug',
        161,
        2013,
        'https://www.imdb.com/title/tt1170358/',
        'https://www.youtube.com/watch?v=OPVWy1tFXuc',
        'https://m.media-amazon.com/images/M/MV5BMzU0NDY0NDEzNV5BMl5BanBnXkFtZTgwOTIxNDU1MDE@._V1_.jpg',
        false,
        null,
        7.6),
       ('The Hobbit',
        'The Battle of the Five Armies',
        144,
        2014,
        'https://www.imdb.com/title/tt2310332/',
        'https://www.youtube.com/watch?v=iVAgTiBrrDA',
        'https://pics.filmaffinity.com/The_Hobbit_The_Battle_of_the_Five_Armies-282438316-large.jpg',
        false,
        null,
        7.9),
       ('Warcraft',
        null,
        123,
        2016,
        'https://www.imdb.com/title/tt0803096/',
        'https://www.youtube.com/watch?v=2Rxoz13Bthc',
        'https://static.posters.cz/image/750/posters/warcraft-one-sheet-i30611.jpg',
        true,
        null,
        8.1),
       ('Iron Man',
        null,
        126,
        2008,
        'https://www.imdb.com/title/tt0371746/',
        'https://www.youtube.com/watch?v=8ugaeA-nMTc',
        'https://www.themoviedb.org/t/p/original/pD4QpqWjsC4LrfB5BkNAFLPajxv.jpg',
        true,
        null,
        9),
       ('Iron Man 2',
        null,
        124,
        2010,
        'https://www.imdb.com/title/tt1228705/',
        'https://www.youtube.com/watch?v=HQxDAX_CBrw',
        'https://m.media-amazon.com/images/I/71VZVXPhmKL._AC_SY679_.jpg',
        true,
        null,
        8.2),
       ('Iron Man 3',
        null,
        150,
        2013,
        'https://www.imdb.com/title/tt1300854/',
        'https://www.youtube.com/watch?v=Ke1Y3P9D0Bc',
        'https://pics.filmaffinity.com/Iron_Man_3-473505612-large.jpg',
        true,
        null,
        6.9),
       ('Thor',
        null,
        115,
        2011,
        'https://www.imdb.com/title/tt0800369/',
        'https://www.youtube.com/watch?v=JOddp-nlNvQ',
        'https://www.themoviedb.org/t/p/original/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg',
        true,
        null,
        7.2),
       ('Thor',
        'The Dark World',
        112,
        2013,
        'https://www.imdb.com/title/tt1981115/',
        'https://www.youtube.com/watch?v=npvJ9FTgZbM',
        'https://media.comicbook.com/wp-content/uploads/2013/09/Thor_Un_Mundo_Oscuro_Poster_Latino_ex_JPosters.jpg',
        true,
        null,
        7.4),
       ('Thor',
        'Ragnarok',
        130,
        2017,
        'https://www.imdb.com/title/tt3501632/',
        'https://www.youtube.com/watch?v=ue80QwXMRHg',
        'https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_.jpg',
        true,
        null,
        7.7);

INSERT INTO movies_genres(movie_entity_id, genres_id)
VALUES (1 , 1),
       (1 , 2),
       (2 , 3),
       (2 , 4),
       (3 , 5),
       (3 , 6),
       (4 , 7),
       (4 , 8),
       (5 , 9),
       (5 , 10),
       (6 , 10),
       (7 , 9),
       (7 , 8),
       (7 , 7),
       (8 , 6),
       (8 , 5),
       (9 , 4),
       (9 , 3),
       (10 , 2),
       (10 , 1),
       (11 , 2),
       (11 , 3),
       (12 , 4),
       (13 , 5),
       (13 , 6),
       (14 , 7),
       (15 , 8),
       (16 , 9),
       (17 , 10),
       (18 , 9),
       (19 , 8),
       (20 , 7);

INSERT INTO movies_platforms(movie_entity_id, platforms_id)
VALUES (1 , 1),
       (2 , 2),
       (3 , 3),
       (3 , 2),
       (4 , 3),
       (4 , 1),
       (5 , 2),
       (6 , 3),
       (7 , 2),
       (8 , 1),
       (9 , 2),
       (10 , 1),
       (11 , 3),
       (12 , 2),
       (13 , 1),
       (14 , 2),
       (15 , 3),
       (16 , 2),
       (17 , 1),
       (18 , 2),
       (18 , 3),
       (19 , 2),
       (20 , 1);