USE `movie-collection`;

INSERT INTO roles(role)
VALUES ('USER');

INSERT INTO users(email, password, username)
VALUES ('hristo@gmail.con' , 'hristo123' , 'hristo');

INSERT INTO users_roles(user_entity_id, roles_id)
VALUES (1 , 1);

INSERT INTO genres(genre)
VALUES ('ACTION');

INSERT INTO genres(genre)
VALUES ('COMEDY');

INSERT INTO genres(genre)
VALUES ('DRAMA');

INSERT INTO genres(genre)
VALUES ('MYSTERY');

INSERT INTO genres(genre)
VALUES ('SCI-FI');

INSERT INTO genres(genre)
VALUES ('ANIMATION');

INSERT INTO genres(genre)
VALUES ('ADVENTURE');

INSERT INTO genres(genre)
VALUES ('FANTASY');

INSERT INTO genres(genre)
VALUES ('ROMANCE');

INSERT INTO genres(genre)
VALUES ('THRILLER');

INSERT INTO genres(genre)
VALUES ('CRIME');

INSERT INTO genres(genre)
VALUES ('DOCUMENTARY');

INSERT INTO genres(genre)
VALUES ('SERIAL');

INSERT INTO platforms(platform)
VALUES ('HBOMAX');

INSERT INTO platforms(platform)
VALUES ('DISNEY+');

INSERT INTO platforms(platform)
VALUES ('NETFLIX');

INSERT INTO platforms(platform)
VALUES ('MY-PC');

INSERT INTO platforms(platform)
VALUES ('EXT_HD');

INSERT INTO movies(title1, title2, duration, year, imdb_url, trailer_url, poster_url, bulgarian_language, description , rating)
VALUES ('The Avengers',
        null,
        143,
        2012,
        'https://www.imdb.com/title/tt0848228/',
        'https://www.youtube.com/watch?v=eOrNdBpGMv8',
        'https://res.cloudinary.com/manoraev/image/upload/v1655050531/Hnet.com-image_izxiba.jpg',
        true,
        null,
        8),
       ('Avengers',
        'Age of Ultron',
        141,
        2015,
        'https://www.imdb.com/title/tt2395427/',
        'https://www.youtube.com/watch?v=zw8QYO_BJYY',
        'https://static.posters.cz/image/750/posters/the-avengers-age-of-ultron-one-sheet-i27861.jpg',
        true,
        null,
        9),
       ('Avengers',
        'Infinity War',
        149,
        2018,
        'https://www.imdb.com/title/tt4154756/',
        'https://www.youtube.com/watch?v=t1QDnIjZlk8',
        'https://static.posters.cz/image/1300/posters/avengers-infinity-war-one-sheet-i122134.jpg',
        true,
        null,
        7),
       ('Avengers',
        'Endgame',
        181,
        2019,
        'https://www.imdb.com/title/tt4154796/',
        'https://www.youtube.com/watch?v=pLvovWcmJ-k',
        'https://static.posters.cz/image/1300/posters/avengers-endgame-journey-s-end-i122136.jpg',
        true,
        null,
        9),
       ('The Dark Knight',
        null,
        152,
        2008,
        'https://www.imdb.com/title/tt0468569/',
        'https://www.youtube.com/watch?v=EXeTwQWrcwY',
        'https://images.pristineauction.com/158/1582578/main_1597378492-The-Dark-Knight-27x40-Movie-Poster-PristineAuction.com.jpg',
        true,
        null,
        8),
       ('The Dark Knight Rises',
        null,
        164,
        2012,
        'https://www.imdb.com/title/tt1345836/',
        'https://www.youtube.com/watch?v=GokKUqLcvD8',
        'https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        7),
       ('Batman Begins',
        null,
        140,
        2005,
        'https://www.imdb.com/title/tt0372784/',
        'https://www.youtube.com/watch?v=FiL1_5DWV7Y',
        'https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
        true,
        null,
        8),
       ('The Lord of the Rings',
        'The Fellowship of the Ring',
        178,
        2001,
        'https://www.imdb.com/title/tt0120737/',
        'https://www.youtube.com/watch?v=_e8QGuG50ro',
        'https://m.media-amazon.com/images/I/81EBp0vOZZL._AC_SY741_.jpg',
        false,
        null,
        8.5),
       ('The Lord of the Rings',
        'The Two Towers',
        179,
        2002,
        'https://www.imdb.com/title/tt0167261/',
        'https://www.youtube.com/watch?v=LbfMDwc4azU',
        'https://www.themoviedb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
        false,
        null,
        9.1),
       ('The Lord of the Rings',
        'The Return of the King',
        201,
        2003,
        'https://www.imdb.com/title/tt0167260/',
        'https://www.youtube.com/watch?v=r5X-hFf6Bwo',
        'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg',
        false,
        null,
        8.7),
       ('The Hobbit',
        'An Unexpected Journey',
        169,
        2012,
        'https://www.imdb.com/title/tt0903624/',
        'https://www.youtube.com/watch?v=SDnYMbYB-nU',
        'https://m.media-amazon.com/images/M/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_FMjpg_UX1000_.jpg',
        false,
        null,
        8.3),
       ('The Hobbit',
        'The Desolation of Smaug',
        161,
        2013,
        'https://www.imdb.com/title/tt1170358/',
        'https://www.youtube.com/watch?v=OPVWy1tFXuc',
        'https://m.media-amazon.com/images/M/MV5BMzU0NDY0NDEzNV5BMl5BanBnXkFtZTgwOTIxNDU1MDE@._V1_.jpg',
        false,
        null,
        7.6),
       ('The Hobbit',
        'The Battle of the Five Armies',
        144,
        2014,
        'https://www.imdb.com/title/tt2310332/',
        'https://www.youtube.com/watch?v=iVAgTiBrrDA',
        'https://flxt.tmsimg.com/assets/p10569555_p_v8_ac.jpg',
        false,
        null,
        7.9),
       ('Warcraft',
        null,
        123,
        2016,
        'https://www.imdb.com/title/tt0803096/',
        'https://www.youtube.com/watch?v=2Rxoz13Bthc',
        'https://static.posters.cz/image/750/posters/warcraft-one-sheet-i30611.jpg',
        true,
        null,
        8.1),
       ('Iron Man',
        null,
        126,
        2008,
        'https://www.imdb.com/title/tt0371746/',
        'https://www.youtube.com/watch?v=8ugaeA-nMTc',
        'https://www.themoviedb.org/t/p/original/pD4QpqWjsC4LrfB5BkNAFLPajxv.jpg',
        true,
        null,
        9),
       ('Iron Man 2',
        null,
        124,
        2010,
        'https://www.imdb.com/title/tt1228705/',
        'https://www.youtube.com/watch?v=HQxDAX_CBrw',
        'https://m.media-amazon.com/images/I/71VZVXPhmKL._AC_SY679_.jpg',
        true,
        null,
        8.2),
       ('Iron Man 3',
        null,
        150,
        2013,
        'https://www.imdb.com/title/tt1300854/',
        'https://www.youtube.com/watch?v=Ke1Y3P9D0Bc',
        'https://m.media-amazon.com/images/M/MV5BMjE5MzcyNjk1M15BMl5BanBnXkFtZTcwMjQ4MjcxOQ@@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        6.9),
       ('Thor',
        null,
        115,
        2011,
        'https://www.imdb.com/title/tt0800369/',
        'https://www.youtube.com/watch?v=JOddp-nlNvQ',
        'https://www.themoviedb.org/t/p/original/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg',
        true,
        null,
        7.2),
       ('Thor',
        'The Dark World',
        112,
        2013,
        'https://www.imdb.com/title/tt1981115/',
        'https://www.youtube.com/watch?v=npvJ9FTgZbM',
        'https://media.comicbook.com/wp-content/uploads/2013/09/Thor_Un_Mundo_Oscuro_Poster_Latino_ex_JPosters.jpg',
        true,
        null,
        7.4),
       ('Thor',
        'Ragnarok',
        130,
        2017,
        'https://www.imdb.com/title/tt3501632/',
        'https://www.youtube.com/watch?v=ue80QwXMRHg',
        'https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_.jpg',
        true,
        null,
        7.7),
       ('Dune',
        null,
        155,
        2021,
        'https://www.imdb.com/title/tt1160419/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=Tqc5cbDe8yU',
        'https://static.posters.cz/image/1300/posters/dune-part-1-i122815.jpg',
        false,
        null,
        8.0),
       ('Reminiscence',
        null,
        114,
        2021,
        'https://www.imdb.com/title/tt3272066/?ref_=nv_sr_srsg_4',
        'https://www.youtube.com/watch?v=5MhpQnAFiFI',
        'https://m.media-amazon.com/images/M/MV5BODBkMTNmMmQtYTNlMy00OTRhLWE5MzgtYTZlMTUyYzY1MzkzXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_FMjpg_UX1000_.jpg',
        false,
        null,
        5.8),
       ('Ocean`s Eight',
        null,
        110,
        2018,
        'https://www.imdb.com/title/tt5164214/',
        'https://www.youtube.com/watch?v=zfEfiLeIWLU',
        'https://m.media-amazon.com/images/M/MV5BMjAyNDEyMzc4Ml5BMl5BanBnXkFtZTgwMjEzNjM0NTM@._V1_.jpg',
        false,
        null,
        6.3),
       ('The Hustle',
        null,
        93,
        2019,
        'https://www.imdb.com/title/tt1298644/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=_j5hwooOHVE',
        'https://m.media-amazon.com/images/I/61kYfihrr4S._AC_SY679_.jpg',
        false,
        null,
        5.4),
       ('Ocean`s Eleven',
        null,
        116,
        2001,
        'https://www.imdb.com/title/tt0240772/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=imm6OR605UI',
        'https://m.media-amazon.com/images/M/MV5BYzVmYzVkMmUtOGRhMi00MTNmLThlMmUtZTljYjlkMjNkMjJkXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg',
        true,
        null,
        7.7),
       ('Ocean`s Twelve',
        null,
        125,
        2004,
        'https://www.imdb.com/title/tt0349903/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=k9uhRSLMORw',
        'https://m.media-amazon.com/images/M/MV5BMmJmYzBjNTktMTJjZS00ZGRhLWE1Y2QtOWQxZGU0Y2RmMjkyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
        true,
        null,
        6.4),
       ('Ocean`s Thirteen',
        null,
        122,
        2007,
        'https://www.imdb.com/title/tt0496806/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=so9Eh-Guci8',
        'https://m.media-amazon.com/images/M/MV5BMTMyNTc1NzY5MV5BMl5BanBnXkFtZTcwNDM4NTQzMw@@._V1_.jpg',
        true,
        null,
        6.9),
       ('The Fast and the Furious',
        null,
        106,
        2001,
        'https://www.imdb.com/title/tt0232500/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=ZsJz2TJAPjw',
        'https://i.pinimg.com/originals/a3/10/a4/a310a49fde199ba03625275282dcac4b.jpg',
        true,
        null,
        6.8),
       ('Fast & Furious',
        null,
        107,
        2009,
        'https://www.imdb.com/title/tt1013752/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=9eBR_u2iRus',
        'https://static.posters.cz/image/1300/posters/fast-furious-4-i114163.jpg',
        true,
        null,
        6.5),
       ('Fast Five',
        null,
        130,
        2011,
        'https://www.imdb.com/title/tt1596343/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=mw2AqdB5EVA',
        'https://www.themoviedb.org/t/p/original/gEfQjjQwY7fh5bI4GlG0RrBu7Pz.jpg',
        true,
        null,
        7.3),
       ('Fast & Furious 6',
        null,
        130,
        2013,
        'https://www.imdb.com/title/tt1905041/',
        'https://www.youtube.com/watch?v=dKi5XoeTN0k',
        'https://m.media-amazon.com/images/M/MV5BMTM3NTg2NDQzOF5BMl5BanBnXkFtZTcwNjc2NzQzOQ@@._V1_.jpg',
        true,
        null,
        7.0),
       ('Furious 7',
        null,
        137,
        2015,
        'https://www.imdb.com/title/tt2820852/',
        'https://www.youtube.com/watch?v=Skpu5HaVkOc',
        'https://m.media-amazon.com/images/I/910VekmDZ5L._AC_SY606_.jpg',
        true,
        null,
        7.1),
       ('The Fate of the Furious',
        null,
        136,
        2017,
        'https://www.imdb.com/title/tt4630562/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=JwMKRevYa_M',
        'https://m.media-amazon.com/images/M/MV5BMjMxODI2NDM5Nl5BMl5BanBnXkFtZTgwNjgzOTk1MTI@._V1_.jpg',
        true,
        null,
        6.6),
       ('F9: The Fast Saga',
        null,
        143,
        2021,
        'https://www.imdb.com/title/tt5433138/',
        'https://www.youtube.com/watch?v=aSiDu3Ywi8E',
        'https://m.media-amazon.com/images/M/MV5BMjI0NmFkYzEtNzU2YS00NTg5LWIwYmMtNmQ1MTU0OGJjOTMxXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_.jpg',
        true,
        null,
        5.2),
       ('Fast & Furious Presents',
        'Hobbs & Shaw',
        137,
        2019,
        'https://www.imdb.com/title/tt6806448/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=HZ7PAyCDwEg',
        'https://moviereviewmom.com/wp-content/uploads/2019/08/Hobbs-and-Shaw.jpg',
        false,
        null,
        6.5),
       ('The Notebook',
        null,
        123,
        2004,
        'https://www.imdb.com/title/tt0332280/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=yDJIcYE32NU',
        'https://m.media-amazon.com/images/I/71Uwp+Uml1L._AC_SL1000_.jpg',
        true,
        null,
        7.8),
       ('The Age of Adaline',
        null,
        112,
        2015,
        'https://www.imdb.com/title/tt1655441/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=7UzSekc0LoQ',
        'https://m.media-amazon.com/images/M/MV5BMTAzMTQzMTA2MjheQTJeQWpwZ15BbWU4MDk2MTg2MzUx._V1_.jpg',
        true,
        null,
        7.2),
       ('Black Panther',
        null,
        134,
        2018,
        'https://www.imdb.com/title/tt1825683/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=xjDjIWPwcPU',
        'https://static.posters.cz/image/750/posters/black-panther-one-sheet-i56194.jpg',
        true,
        null,
        7.3),
       ('Captain Marvel',
        null,
        123,
        2019,
        'https://www.imdb.com/title/tt4154664/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=Z1BCujX3pw8',
        'https://static.posters.cz/image/750/posters/captain-marvel-higher-further-faster-i70045.jpg',
        false,
        null,
        6.8),
       ('Captain America',
        'The First Avenger',
        124,
        2011,
        'https://www.imdb.com/title/tt0458339/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=JerVrbLldXw',
        'https://static.posters.cz/image/1300/posters/marvel-captain-america-i34925.jpg',
        true,
        null,
        6.9),
       ('Captain America',
        'The Winter Soldier',
        136,
        2014,
        'https://www.imdb.com/title/tt1843866/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=7SlILk2WMTI',
        'https://static.posters.cz/image/1300/posters/captain-america-winter-soldier-one-sheet-i19272.jpg',
        true,
        null,
        7.8),
       ('Captain America',
        'Civil War',
        147,
        2016,
        'https://www.imdb.com/title/tt3498820/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=dKrVegVI0Us',
        'https://static.posters.cz/image/750/posters/captain-america-civil-war-one-sheet-i30823.jpg',
        true,
        null,
        7.8),
       ('Spider-Man',
        'No Way Home',
        148,
        2021,
        'https://www.imdb.com/title/tt10872600/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=JfVOs4VSpmA',
        'https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UX1000_.jpg',
        false,
        null,
        8.3),
       ('Spider-Man',
        'Far from Home',
        129,
        2019,
        'https://www.imdb.com/title/tt6320628/?ref_=nv_sr_srsg_11',
        'https://www.youtube.com/watch?v=DYYtuKyMtY8',
        'https://www.themoviedb.org/t/p/original/3WES2GZ7PGzscIqvqhsUcvoC5Kc.jpg',
        false,
        null,
        7.4),
       ('Doctor Strange',
        null,
        112,
        2016,
        'https://www.imdb.com/title/tt1211837/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=HSzx-zryEgM',
        'https://static.posters.cz/image/750/posters/doctor-strange-portal-i33477.jpg',
        true,
        null,
        7.5),
       ('Wonder Woman',
        null,
        141,
        2017,
        'https://www.imdb.com/title/tt0451279/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=1Q8fG0TtVAY',
        'https://m.media-amazon.com/images/M/MV5BMTYzODQzYjQtNTczNC00MzZhLTg1ZWYtZDUxYmQ3ZTY4NzA1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_FMjpg_UX1000_.jpg',
        false,
        null,
        7.4),
       ('Wonder Woman 1984',
        null,
        151,
        2020,
        'https://www.imdb.com/title/tt7126948/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=sfM7_JLk-84',
        'https://static.posters.cz/image/750/posters/wonder-woman-1984-neon-static-i84057.jpg',
        true,
        null,
        5.4),
       ('Man of Steel',
        null,
        143,
        2013,
        'https://www.imdb.com/title/tt0770828/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=T6DJcgm3wNY',
        'https://m.media-amazon.com/images/I/61TISXNqC4L._AC_SY679_.jpg',
        true,
        null,
        7.1),
       ('Batman v Superman',
        'Dawn of Justice',
        152,
        2016,
        'https://www.imdb.com/title/tt2975590/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=0WWzgGyAH6Y',
        'https://static.posters.cz/image/750/posters/batman-v-superman-dawn-of-justice-one-sheet-i29162.jpg',
        false,
        null,
        6.4),
       ('World War Z',
        null,
        116,
        2013,
        'https://www.imdb.com/title/tt0816711/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=Md6Dvxdr0AQ',
        'https://static.posters.cz/image/750/posters/world-war-z-one-sheet-i14349.jpg',
        true,
        null,
        7.0),
       ('Aquaman',
        null,
        143,
        2018,
        'https://www.imdb.com/title/tt1477834/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=WDkg3h8PCVU',
        'https://cdn11.bigcommerce.com/s-ydriczk/images/stencil/1280x1280/products/88758/92243/Aquaman-Regular-Style-B-Aquaman-and-Mera-Poster-buy-original-movie-posters-at-starstills__01319.1547485197.jpg?c=2',
        false,
        null,
        6.8),
       ('Mr. & Mrs. Smith',
        null,
        120,
        2005,
        'https://www.imdb.com/title/tt0356910/?ref_=nv_sr_srsg_6',
        'https://www.youtube.com/watch?v=CZ0B22z22pI',
        'https://m.media-amazon.com/images/M/MV5BMTUxMzcxNzQzOF5BMl5BanBnXkFtZTcwMzQxNjUyMw@@._V1_.jpg',
        true,
        null,
        6.5),
       ('Justice League',
        null,
        120,
        2017,
        'https://www.imdb.com/title/tt0974015/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=3cxixDgHUYw',
        'https://static.posters.cz/image/750/posters/justice-league-movie-save-the-world-i50049.jpg',
        true,
        null,
        6.1),
       ('National Treasure',
        null,
        131,
        2004,
        'https://www.imdb.com/title/tt0368891/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=vqUPxNT8io4',
        'https://m.media-amazon.com/images/M/MV5BMTY3NTc4OTYxMF5BMl5BanBnXkFtZTcwMjk5NzUyMw@@._V1_.jpg',
        true,
        null,
        6.9),
       ('National Treasure',
        'Book of Secrets',
        124,
        2007,
        'https://www.imdb.com/title/tt0465234/?ref_=fn_al_tt_4',
        'https://www.youtube.com/watch?v=lq6MlrkFHG0',
        'https://m.media-amazon.com/images/M/MV5BMTU2NTM3NjU1N15BMl5BanBnXkFtZTcwODg1MDU1MQ@@._V1_.jpg',
        true,
        null,
        6.5),
       ('King Arthur',
        'Legend of the Sword',
        126,
        2017,
        'https://www.imdb.com/title/tt1972591/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=jIM4-HLtUM0',
        'https://m.media-amazon.com/images/M/MV5BMjM3ODY3Njc5Ml5BMl5BanBnXkFtZTgwMjQ5NjM5MTI@._V1_.jpg',
        false,
        null,
        6.7),
       ('Uncharted',
        null,
        116,
        2022,
        'https://www.imdb.com/title/tt1464335/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=eHp3MbsCbMg',
        'https://assets-prd.ignimgs.com/2022/01/13/uncharted-poster-full-1642086040683.jpg',
        false,
        null,
        6.4),
       ('John Wick',
        null,
        101,
        2014,
        'https://www.imdb.com/title/tt2911666/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=C0BMx-qxsP4',
        'https://m.media-amazon.com/images/I/81F5PF9oHhL._AC_SL1500_.jpg',
        true,
        null,
        7.4),
       ('John Wick',
        'Chapter 2',
        122,
        2017,
        'https://www.imdb.com/title/tt4425200/?ref_=fn_al_tt_3',
        'https://www.youtube.com/watch?v=XGk2EfbD_Ps',
        'https://m.media-amazon.com/images/M/MV5BMjE2NDkxNTY2M15BMl5BanBnXkFtZTgwMDc2NzE0MTI@._V1_.jpg',
        false,
        null,
        7.4),
       ('John Wick',
        'Chapter 3 - Parabellum',
        130,
        2019,
        'https://www.imdb.com/title/tt6146586/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=M7XM597XO94',
        'https://m.media-amazon.com/images/I/91XKS5MN9uL._AC_SY741_.jpg',
        false,
        null,
        7.4),
       ('Gone in 60 Seconds',
        null,
        118,
        2000,
        'https://www.imdb.com/title/tt0187078/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=hh8uvTlmh0w',
        'https://m.media-amazon.com/images/I/71i9kY-0-ZL._AC_SY679_.jpg',
        true,
        null,
        6.5),
       ('Ford v Ferrari',
        null,
        152,
        2019,
        'https://www.imdb.com/title/tt1950186/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=zyYgDtY2AMY',
        'https://m.media-amazon.com/images/M/MV5BM2UwMDVmMDItM2I2Yi00NGZmLTk4ZTUtY2JjNTQ3OGQ5ZjM2XkEyXkFqcGdeQXVyMTA1OTYzOTUx._V1_.jpg',
        false,
        null,
        8.1),
       ('Edge of Tomorrow',
       null,
        113,
        2014,
        'https://www.imdb.com/title/tt1631867/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=vw61gCe2oqI',
        'https://m.media-amazon.com/images/I/71VxOTvurAL._AC_SY679_.jpg',
        false,
        null,
        7.9),
       ('Jason Bourne',
        null,
        123,
        2016,
        'https://www.imdb.com/title/tt4196776/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=v71ce1Dqqns',
        'https://m.media-amazon.com/images/M/MV5BNGJlYjVkMjQtN2NlZC00NTJhLThmZjItMTRlZDczMmE3YmI3XkEyXkFqcGdeQXVyMzI0NDc4ODY@._V1_.jpg',
        false,
        null,
        6.6),
       ('The Bourne Identity',
        null,
        119,
        2002,
        'https://www.imdb.com/title/tt0258463/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=FpKaB5dvQ4g',
        'https://m.media-amazon.com/images/M/MV5BM2JkNGU0ZGMtZjVjNS00NjgyLWEyOWYtZmRmZGQyN2IxZjA2XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg',
        true,
        null,
        7.9),
       ('The Bourne Supremacy',
        null,
        108,
        2004,
        'https://www.imdb.com/title/tt0372183/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=Y-HqyyfBbSo',
        'https://www.themoviedb.org/t/p/original/ltEjxNMnmY7atJ9PpcEmCwM5ItR.jpg',
        true,
        null,
        7.7),
       ('The Bourne Ultimatum',
        null,
        115,
        2007,
        'https://www.imdb.com/title/tt0440963/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=ZT2ZxjUjSo0',
        'https://i.pinimg.com/originals/d4/f8/5c/d4f85ca3b923e62db2cf03727499feee.jpg',
        true,
        null,
        8.0),
       ('The Bourne Legacy',
        null,
        135,
        2012,
        'https://www.imdb.com/title/tt1194173/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=jSzy9qQ3mDE',
        'https://m.media-amazon.com/images/M/MV5BMTc4Njk3MDM1Nl5BMl5BanBnXkFtZTcwODgyOTMxOA@@._V1_.jpg',
        false,
        null,
        6.6),
       ('Sherlock Holmes',
        null,
        128,
        2009,
        'https://www.imdb.com/title/tt0988045/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=J7nJksXDBWc',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPr5Ufq-Qe3_9yygO-dphop1yVAIC4diBiFg&usqp=CAU',
        true,
        null,
        7.6),
       ('Sherlock Holmes',
        'A Game of Shadows',
        129,
        2011,
        'https://www.imdb.com/title/tt1515091/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=V1OYiPa-eLg',
        'https://m.media-amazon.com/images/M/MV5BMTQwMzQ5Njk1MF5BMl5BanBnXkFtZTcwNjIxNzIxNw@@._V1_.jpg',
        true,
        null,
        7.4),
       ('Dear John',
        null,
        108,
        2010,
        'https://www.imdb.com/title/tt0989757/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=r0fq5dd0C60',
        'https://m.media-amazon.com/images/I/71BBiNYXbLL._AC_SY679_.jpg',
        true,
        null,
        6.3),
       ('Catch Me If You Can',
        null,
        141,
        2002,
        'https://www.imdb.com/title/tt0264464/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=s-7pyIxz8Qg',
        'https://m.media-amazon.com/images/M/MV5BZWNjNGRmNGEtYjRjNS00YzEwLWExZmEtMzAzMDhiMjFhZGRiXkEyXkFqcGdeQXVyMjQ0NzE0MQ@@._V1_.jpg',
        true,
        null,
        8.1),
       ('The Wolf of Wall Street',
        null,
        180,
        2013,
        'https://www.imdb.com/title/tt0993846/?ref_=nv_sr_srsg_6',
        'https://www.youtube.com/watch?v=iszwuX1AK6A',
        'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_.jpg',
        true,
        null,
        8.2),
       ('Limitless',
        null,
        105,
        2011,
        'https://www.imdb.com/title/tt1219289/?ref_=nv_sr_srsg_4',
        'https://www.youtube.com/watch?v=4TLppsfzQH8',
        'https://m.media-amazon.com/images/M/MV5BYmViZGM0MGItZTdiYi00ZDU4LWIxNDYtNTc1NWQ5Njc2N2YwXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        7.4),
       ('Ghosts of Girlfriends Past',
        null,
        100,
        2009,
        'https://www.imdb.com/title/tt0821640/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=LUUIY7Fnzts',
        'https://m.media-amazon.com/images/M/MV5BMTA0Njk2NTIyMTVeQTJeQWpwZ15BbWU3MDU0MzUyMzI@._V1_.jpg',
        true,
        null,
        5.8),
       ('Harry Potter and the Sorcerer`s Stone',
        null,
        152,
        2001,
        'https://www.imdb.com/title/tt0241527/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=mNgwNXKBEW0',
        'https://cdn.europosters.eu/image/1300/posters/harry-potter-philosopher-s-stone-i104639.jpg',
        true,
        null,
        7.6),
       ('Harry Potter and the Chamber of Secrets',
        null,
        161,
        2002,
        'https://www.imdb.com/title/tt0295297/?ref_=nv_sr_srsg_8',
        'https://www.youtube.com/watch?v=jBltxS8HfQ4',
        'https://www.themoviedb.org/t/p/original/csOv5H7R2zdnKaYuTrGVWohmo8d.jpg',
        true,
        null,
        7.4),
       ('Harry Potter and the Prisoner of Azkaban',
        null,
        142,
        2004,
        'https://www.imdb.com/title/tt0304141/?ref_=nv_sr_srsg_9',
        'https://www.youtube.com/watch?v=lAxgztbYDbs',
        'https://cdn.europosters.eu/image/1300/art-photo/harry-potter-the-prisoner-of-azkaban-i105075.jpg',
        true,
        null,
        7.9),
       ('Harry Potter and the Goblet of Fire',
        null,
        157,
        2005,
        'https://www.imdb.com/title/tt0330373/?ref_=nv_sr_srsg_6',
        'https://www.youtube.com/watch?v=3EGojp4Hh6I',
        'https://www.themoviedb.org/t/p/original/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg',
        true,
        null,
        7.7),
       ('Harry Potter and the Order of the Phoenix',
        null,
        138,
        2007,
        'https://www.imdb.com/title/tt0373889/?ref_=nv_sr_srsg_10',
        'https://www.youtube.com/watch?v=y6ZW7KXaXYk',
        'https://cdn.europosters.eu/image/1300/art-photo/harry-potter-order-of-the-phoenix-i115696.jpg',
        true,
        null,
        7.5),
       ('Harry Potter and the Half-Blood Prince',
        null,
        153,
        2009,
        'https://www.imdb.com/title/tt0417741/?ref_=nv_sr_srsg_11',
        'https://www.youtube.com/watch?v=sg81Lts5kYY',
        'https://www.themoviedb.org/t/p/w500/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg',
        true,
        null,
        7.6),
       ('Harry Potter and the Deathly Hallows',
        'Part 1',
        146,
        2010,
        'https://www.imdb.com/title/tt0926084/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=MxqsmsA8y5k',
        'https://m.media-amazon.com/images/M/MV5BMTQ2OTE1Mjk0N15BMl5BanBnXkFtZTcwODE3MDAwNA@@._V1_.jpg',
        true,
        null,
        7.7),
       ('Harry Potter and the Deathly Hallows',
        'Part 2',
        130,
        2011,
        'https://www.imdb.com/title/tt1201607/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=5NYt1qirBWg',
        'https://www.themoviedb.org/t/p/original/c54HpQmuwXjHq2C9wmoACjxoom3.jpg',
        true,
        null,
        8.1),
       ('The Transporter',
        null,
        92,
        2002,
        'https://www.imdb.com/title/tt0293662/?ref_=nv_sr_srsg_1',
        'https://www.youtube.com/watch?v=7FnbLyv2oio',
        'https://cdn.shopify.com/s/files/1/1416/8662/products/transporter_2002_original_film_art_600x.jpg?v=1572287768',
        true,
        null,
        6.8),
       ('Transporter 2',
        null,
        87,
        2005,
        'https://www.imdb.com/title/tt0388482/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=_KFOYFBh2QM',
        'https://m.media-amazon.com/images/M/MV5BMTQ5MDM0MTI2N15BMl5BanBnXkFtZTcwNTM5NDczMw@@._V1_.jpg',
        true,
        null,
        6.3),
       ('Transporter 3',
        null,
        104,
        2008,
        'https://www.imdb.com/title/tt1129442/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=Pbh3CDBNIQA',
        'https://static0.srcdn.com/wp-content/uploads/final-transporter-3-poster.jpg?dpr=1.5',
        true,
        null,
        6.0),
       ('Pirates of the Caribbean',
        'The Curse of the Black Pearl',
        143,
        2003,
        'https://www.imdb.com/title/tt0325980/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=naQr0uTrH_s',
        'https://m.media-amazon.com/images/M/MV5BNGYyZGM5MGMtYTY2Ni00M2Y1LWIzNjQtYWUzM2VlNGVhMDNhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
        true,
        null,
        8.1),
       ('Pirates of the Caribbean',
        'Dead Man`s Chest',
        151,
        2006,
        'https://www.imdb.com/title/tt0383574/?ref_=nv_sr_srsg_6',
        'https://www.youtube.com/watch?v=6-NGPgX-uYA',
        'https://m.media-amazon.com/images/M/MV5BMTcwODc1MTMxM15BMl5BanBnXkFtZTYwMDg1NzY3._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        7.3),
       ('Pirates of the Caribbean',
        'At World`s End',
        169,
        2007,
        'https://www.imdb.com/title/tt0449088/?ref_=nv_sr_srsg_8',
        'https://www.youtube.com/watch?v=HKSZtp_OGHY',
        'https://cdn-products.eneba.com/resized-products/5228Fg1_350x200_3x-0.jpg',
        true,
        null,
        7.1),
       ('Pirates of the Caribbean',
        'On Stranger Tides',
        136,
        2011,
        'https://www.imdb.com/title/tt1298650/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=t5AqJww06bw',
        'https://m.media-amazon.com/images/M/MV5BMjE5MjkwODI3Nl5BMl5BanBnXkFtZTcwNjcwMDk4NA@@._V1_.jpg',
        true,
        null,
        6.6),
       ('Pirates of the Caribbean',
        'Dead Men Tell No Tales',
        129,
        2017,
        'https://www.imdb.com/title/tt1790809/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=Hgeu5rhoxxY',
        'https://m.media-amazon.com/images/M/MV5BMTYyMTcxNzc5M15BMl5BanBnXkFtZTgwOTg2ODE2MTI@._V1_.jpg',
        true,
        null,
        6.5),
       ('The Hangover',
        null,
        100,
        2009,
        'https://www.imdb.com/title/tt1119646/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=tcdUhdOlz9M',
        'https://i.pinimg.com/originals/7a/73/6d/7a736d1cd4bc02005c6381eefc34c1e1.jpg',
        true,
        null,
        7.7),
       ('The Hangover Part II',
        null,
        102,
        2011,
        'https://www.imdb.com/title/tt1411697/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=ohF5ZO_zOYU',
        'https://collider.com/wp-content/uploads/the-hangover-part-2-movie-poster-01.jpg',
        true,
        null,
        6.4),
       ('The Hangover Part III',
        null,
        100,
        2013,
        'https://www.imdb.com/title/tt1951261/?ref_=nv_sr_srsg_6',
        'https://www.youtube.com/watch?v=96TelFMZwHc',
        'https://m.media-amazon.com/images/M/MV5BMTA0NjE1MzMzODheQTJeQWpwZ15BbWU3MDY4MTQ3Mzk@._V1_.jpg',
        true,
        null,
        5.8),
       ('Home Alone',
        null,
        103,
        1990,
        'https://www.imdb.com/title/tt0099785/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=jEDaVHmw7r4',
        'https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
        true,
        null,
        7.7),
       ('Home Alone 2',
        'Lost in New York',
        120,
        1992,
        'https://www.imdb.com/title/tt0104431/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=5h9VDUNtoto',
        'https://m.media-amazon.com/images/M/MV5BNDI1MzM0Y2YtYmIyMS00ODE3LTlhZjEtZTUyNmEzMTNhZWU5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
        true,
        null,
        6.8),
       ('Father of the Bride',
        null,
        105,
        1991,
        'https://www.imdb.com/title/tt0101862/?ref_=fn_al_tt_3',
        'https://www.youtube.com/watch?v=qAMYbV20_fA',
        'https://img.moviepostershop.com/father-of-the-bride-movie-poster-1991-1020190489.jpg',
        true,
        null,
        6.5),
       ('Father of the Bride Part II',
        null,
        106,
        1995,
        'https://www.imdb.com/title/tt0113041/?ref_=nv_sr_srsg_6',
        'https://www.youtube.com/watch?v=BbvnDlu_Zjc',
        'https://m.media-amazon.com/images/M/MV5BOTEyNzg5NjYtNDU4OS00MWYxLWJhMTItYWU4NTkyNDBmM2Y0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY1200_CR90,0,630,1200_AL_.jpg',
        true,
        null,
        6.0),
       ('American Pie',
        null,
        95,
        1999,
        'https://www.imdb.com/title/tt0163651/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=iUZ3Yxok6N8',
        'https://www.themoviedb.org/t/p/original/mWrVAXmmC2iZVDyGXlLJOF09KnN.jpg',
        true,
        null,
        7.8),
       ('American Pie 2',
        null,
        108,
        2001,
        'https://www.imdb.com/title/tt0252866/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=FLWu4KewJlU',
        'https://c8.alamy.com/comp/BPHHB5/film-poster-american-pie-2-2001-BPHHB5.jpg',
        true,
        null,
        6.4),
       ('American Wedding',
        null,
        96,
        2003,
        'https://www.imdb.com/title/tt0328828/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=idEa4VrYSbw',
        'https://m.media-amazon.com/images/M/MV5BMTAwNTIzNDk1MDVeQTJeQWpwZ15BbWU3MDMwNzAwMDE@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        6.3),
       ('American Reunion',
        null,
        113,
        2012,
        'https://www.imdb.com/title/tt1605630/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=1akixU65dDY',
        'https://m.media-amazon.com/images/M/MV5BMTY4MTEyMzU1N15BMl5BanBnXkFtZTcwNDQ0NTc1Nw@@._V1_.jpg',
        true,
        null,
        6.7),
       ('Grown Ups',
        null,
        102,
        2010,
        'https://www.imdb.com/title/tt1375670/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=e01NVCveGkg',
        'https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/chameleon/title-movie/230599_GROWN%20UPS%20_2010_1400x2100_English.jpg?itok=Wumkl75R',
        true,
        null,
        5.9),
       ('Grown Ups 2',
        null,
        101,
        2013,
        'https://www.imdb.com/title/tt2191701/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=a_c3hW0Uyvc',
        'https://m.media-amazon.com/images/M/MV5BNTZkZDhjZTEtZjA5MC00MDU2LTk3NDItNzA2YzQ4Y2Q5NjZhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg',
        true,
        null,
        5.3),
       ('Tag',
        null,
        100,
        2018,
        'https://www.imdb.com/title/tt2854926/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=kjC1zmZo30U',
        'https://www.themoviedb.org/t/p/original/iSkDysbfeezj8adgSvnHvaziqft.jpg',
        true,
        null,
        6.5),
       ('The Town',
        null,
        125,
        2010,
        'https://www.imdb.com/title/tt0840361/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=WcXt9aUMbBk',
        'https://c8.alamy.com/comp/EFBGFG/movie-poster-the-town-2010-EFBGFG.jpg',
        true,
        null,
        7.5),
       ('Armageddon',
        null,
        100,
        1998,
        'https://www.imdb.com/title/tt0120591/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=kg_jH47u480',
        'https://i.pinimg.com/originals/88/e9/1b/88e91b9f7e601c0cea79719ddea8180d.jpg',
        true,
        null,
        6.7),
       ('Law Abiding Citizen',
        null,
        109,
        2009,
        'https://www.imdb.com/title/tt1197624/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=LX6kVRsdXW4',
        'https://m.media-amazon.com/images/M/MV5BNTQ1NmZlNDktZTg0NS00ZjNhLTk5M2QtNzExNjUzY2MwMjliXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        7.4),
       ('The Ugly Truth',
        null,
        96,
        2009,
        'https://www.imdb.com/title/tt1142988/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=DvsZtGxsvV0',
        'https://xl.movieposterdb.com/09_10/2009/1142988/xl_1142988_98fd3e6d.jpg',
        true,
        null,
        6.4),
       ('The Bounty Hunter',
        null,
        110,
        2010,
        'https://www.imdb.com/title/tt1038919/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=i3tsaNcem9M',
        'https://picfiles.alphacoders.com/131/131549.jpg',
        true,
        null,
        5.5),
       ('Shang-Chi and the Legend of the Ten Rings',
        null,
        132,
        2021,
        'https://www.imdb.com/title/tt9376612/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=8YjFbMbfXaQ',
        'https://m.media-amazon.com/images/M/MV5BNTliYjlkNDQtMjFlNS00NjgzLWFmMWEtYmM2Mzc2Zjg3ZjEyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
        true,
        null,
        7.4),
       ('47 Ronin',
        null,
        128,
        2013,
        'https://www.imdb.com/title/tt1335975/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=j8cKdDkkIYY',
        'https://m.media-amazon.com/images/M/MV5BMTc0MjE2NzE0OV5BMl5BanBnXkFtZTgwNTU5MjE1MDE@._V1_.jpg',
        true,
        null,
        6.2),
       ('Mulan',
        null,
        115,
        2020,
        'https://www.imdb.com/title/tt4566758/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=KK8FHdFluOQ',
        'https://m.media-amazon.com/images/M/MV5BNDliY2E1MjUtNzZkOS00MzJlLTgyOGEtZDg4MTI1NzZkMTBhXkEyXkFqcGdeQXVyNjMwMzc3MjE@._V1_.jpg',
        true,
        null,
        5.7),
       ('The Great Wall',
        null,
        103,
        2016,
        'https://www.imdb.com/title/tt2034800/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=avF6GHyyk5c',
        'https://www.themoviedb.org/t/p/original/p70dq1YxabemdZDm5K6Q8G10wSn.jpg',
        true,
        null,
        5.9),
       ('The Shawshank Redemption',
        null,
        142,
        1994,
        'https://www.imdb.com/title/tt0111161/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=1a264172-ae11-42e4-8ef7-7fed1973bb8f&pf_rd_r=W7BX69SDGV31862AJWHX&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_tt_1',
        'https://www.youtube.com/watch?v=6hB3S9bIaco',
        'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        9.3),
       ('Inception',
        null,
        148,
        2010,
        'https://www.imdb.com/title/tt1375666/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=1a264172-ae11-42e4-8ef7-7fed1973bb8f&pf_rd_r=W7BX69SDGV31862AJWHX&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_tt_13',
        'https://www.youtube.com/watch?v=YoHD9XEInc0',
        'https://i.pinimg.com/originals/5f/7d/b2/5f7db2ce6f1258afee6218528f0ea2fa.jpg',
        true,
        null,
        8.8),
       ('The Matrix',
        null,
        136,
        1999,
        'https://www.imdb.com/title/tt0133093/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=1a264172-ae11-42e4-8ef7-7fed1973bb8f&pf_rd_r=W7BX69SDGV31862AJWHX&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_tt_16',
        'https://www.youtube.com/watch?v=vKQi3bBA1y8',
        'https://www.themoviedb.org/t/p/original/vybQQ7w7vGvF53IsGD0y0JSgIsA.jpg',
        true,
        null,
        8.7),
       ('The Matrix',
        'Reloaded',
        138,
        2003,
        'https://www.imdb.com/title/tt0234215/?ref_=nv_sr_srsg_6',
        'https://www.youtube.com/watch?v=kYzz0FSgpSU',
        'https://m.media-amazon.com/images/M/MV5BODE0MzZhZTgtYzkwYi00YmI5LThlZWYtOWRmNWE5ODk0NzMxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
        true,
        null,
        7.2),
       ('The Matrix',
        'Revolutions',
        129,
        2003,
        'https://www.imdb.com/title/tt0242653/?ref_=nv_sr_srsg_7',
        'https://www.youtube.com/watch?v=hMbexEPAOQI',
        'https://i.pinimg.com/originals/45/68/84/456884018019425dd45dd5f822274ca2.jpg',
        true,
        null,
        6.7),
       ('The Matrix',
        'Resurrections',
        148,
        2021,
        'https://www.imdb.com/title/tt10838180/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=9ix7TUGVYIo',
        'https://m.media-amazon.com/images/M/MV5BMGJkNDJlZWUtOGM1Ny00YjNkLThiM2QtY2ZjMzQxMTIxNWNmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg',
        false,
        null,
        5.7),
       ('Se7en',
        null,
        127,
        1995,
        'https://www.imdb.com/title/tt0114369/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=1a264172-ae11-42e4-8ef7-7fed1973bb8f&pf_rd_r=W7BX69SDGV31862AJWHX&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_tt_19',
        'https://www.youtube.com/watch?v=znmZoVkCjpI',
        'https://i.pinimg.com/originals/2a/d3/b5/2ad3b5c9c290fabca92f11fbf52594e4.jpg',
        false,
        null,
        8.6),
       ('The Green Mile',
        null,
        189,
        1999,
        'https://www.imdb.com/title/tt0120689/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=1a264172-ae11-42e4-8ef7-7fed1973bb8f&pf_rd_r=W7BX69SDGV31862AJWHX&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_tt_26',
        'https://www.youtube.com/watch?v=Ki4haFrqSrw',
        'https://i.pinimg.com/originals/69/f9/2f/69f92f0ac390e1b571c515c3f8dd6d15.jpg',
        false,
        null,
        8.6),
       ('The Prestige',
        null,
        150,
        2006,
        'https://www.imdb.com/title/tt0482571/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=1a264172-ae11-42e4-8ef7-7fed1973bb8f&pf_rd_r=W7BX69SDGV31862AJWHX&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_tt_41',
        'https://www.youtube.com/watch?v=RLtaA9fFNXU',
        'https://c8.alamy.com/comp/DT67F9/hugh-jackman-scarlett-johansson-christian-bale-poster-the-prestige-DT67F9.jpg',
        false,
        null,
        8.5),
       ('Coco',
        null,
        105,
        2017,
        'https://www.imdb.com/title/tt2380307/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=1a264172-ae11-42e4-8ef7-7fed1973bb8f&pf_rd_r=W7BX69SDGV31862AJWHX&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_tt_76',
        'https://www.youtube.com/watch?v=Ga6RYejo6Hk',
        'https://i.pinimg.com/originals/7a/6d/c4/7a6dc4222a7bd3037d9f7146314e3bc7.jpg',
        false,
        null,
        8.4),
       ('Up',
        null,
        96,
        2009,
        'https://www.imdb.com/title/tt1049413/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=1a264172-ae11-42e4-8ef7-7fed1973bb8f&pf_rd_r=W7BX69SDGV31862AJWHX&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_tt_112',
        'https://www.youtube.com/watch?v=ORFWdXl_zJ4',
        'https://wallpapers.com/images/high/up-disney-movie-poster-nvg1a0gcul84mph6.jpg',
        false,
        null,
        8.3),
       ('Jurassic World',
        null,
        124,
        2015,
        'https://www.imdb.com/title/tt0369610/?ref_=nv_sr_srsg_6',
        'https://www.youtube.com/watch?v=RFinNxS5KN4',
        'https://picfiles.alphacoders.com/357/357474.jpg',
        false,
        null,
        6.9),
       ('Jurassic World',
        'Fallen Kingdom',
        128,
        2018,
        'https://www.imdb.com/title/tt4881806/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=vn9mMeWcgoM',
        'https://m.media-amazon.com/images/M/MV5BNTg0NzVlMzItMWE3ZC00MWUxLWJjM2EtOGNhNTE1ODQ0ZDBiXkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg',
        false,
        null,
        6.1),
       ('Kong',
        'Skull Island',
        118,
        2017,
        'https://www.imdb.com/title/tt3731562/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=44LdLqgOpjo',
        'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5782/5782302_so.jpg',
        false,
        null,
        6.6),
       ('Inside Out',
        null,
        95,
        2015,
        'https://www.imdb.com/title/tt2096673/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=1a264172-ae11-42e4-8ef7-7fed1973bb8f&pf_rd_r=W7BX69SDGV31862AJWHX&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_tt_161',
        'https://www.youtube.com/watch?v=yRUAzGQ3nSY',
        'https://i.pinimg.com/originals/6d/71/e7/6d71e72ccb7199f965f6b8106267a8e8.jpg',
        false,
        null,
        8.2),
       ('Venom',
        null,
        112,
        2018,
        'https://www.imdb.com/title/tt1270797/?ref_=nv_sr_srsg_7',
        'https://www.youtube.com/watch?v=u9Mv98Gr5pY',
        'https://i.pinimg.com/originals/af/30/dc/af30dc9af76c0b93a3d9a0cdd7954af2.jpg',
        false,
        null,
        6.6),
       ('Venom',
        'Let There Be Carnage',
        97,
        2021,
        'https://www.imdb.com/title/tt7097896/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=-FmWuCgJmxo',
        'https://m.media-amazon.com/images/M/MV5BN2I2Yzc2OWMtMWQzYi00ZDcxLTgyOTMtNjBiNzA5Y2QxZDYxXkEyXkFqcGdeQXVyMTM0NTc2NDgw._V1_.jpg',
        false,
        null,
        5.9),
       ('A Dog`s Purpose',
        null,
        100,
        2017,
        'https://www.imdb.com/title/tt1753383/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=1jLOOCADTGs',
        'https://m.media-amazon.com/images/M/MV5BZmI2OGEyZmYtNmVlZS00ODAyLTlmZTMtMDJiZjg1Zjg2MGRlXkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg',
        true,
        null,
        7.2),
       ('A Dog`s Journey',
        null,
        109,
        2019,
        'https://www.imdb.com/title/tt8385474/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=A2FrrSyyKfA',
        'https://m.media-amazon.com/images/M/MV5BYjRhMWY0ODMtMmM3OC00ZGRmLWIyZjktZGQ0ZGE4MzcyZWE5XkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_.jpg',
        true,
        null,
        7.4),
       ('Rush',
        null,
        123,
        2013,
        'https://www.imdb.com/title/tt1979320/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=4XA73ni9eVs',
        'https://m.media-amazon.com/images/M/MV5BOWEwODJmZDItYTNmZC00OGM4LThlNDktOTQzZjIzMGQxODA4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
        true,
        null,
        8.1),
       ('Alita',
        'Battle Angel',
        122,
        2019,
        'https://www.imdb.com/title/tt0437086/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=w7pYhpJaJW8',
        'https://m.media-amazon.com/images/M/MV5BMTQzYWYwYjctY2JhZS00NTYzLTllM2UtZWY5ZTk0NmYwYzIyXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg',
        false,
        null,
        7.3),
       ('X-Men',
        'Dark Phoenix',
        123,
        2013,
        'https://www.imdb.com/title/tt6565702/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=1-q8C_c-nlM',
        'https://m.media-amazon.com/images/M/MV5BMmZmYTgwZGItNDIxMS00MmRkLWEzODQtYTllNzM0ZWE1NmQ5XkEyXkFqcGdeQXVyODQzNTE3ODc@._V1_.jpg',
        true,
        null,
        5.7),
       ('The Addams Family',
        null,
        86,
        2019,
        'https://www.imdb.com/title/tt1979320/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=xFCrR3Uw6Mk',
        'https://m.media-amazon.com/images/M/MV5BODBjOTAzZmMtNGJkOC00M2M3LWI1MTctZjZlMzdiODBkMzc0XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_.jpg',
        true,
        null,
        5.8),
       ('The Adjustment Bureau',
        null,
        106,
        2011,
        'https://www.imdb.com/title/tt1385826/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=wZJ0TP4nTaE',
        'https://m.media-amazon.com/images/M/MV5BMzc0ZDcwZTYtOWUzZi00NDE4LWI4NjgtMWVjZTUyYTA2ZTNhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg',
        true,
        null,
        7.0),
       ('Despicable Me',
        null,
        95,
        2010,
        'https://www.imdb.com/title/tt1323594/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=zzCZ1W_CUoI',
        'https://m.media-amazon.com/images/M/MV5BMTY3NjY0MTQ0Nl5BMl5BanBnXkFtZTcwMzQ2MTc0Mw@@._V1_.jpg',
        true,
        null,
        7.6),
       ('Despicable Me 2',
        null,
        98,
        2013,
        'https://www.imdb.com/title/tt1690953/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=yM9sKpQOuEw',
        'https://static.wikia.nocookie.net/despicableme/images/6/6a/Gru.jpeg/revision/latest?cb=20210119032211',
        true,
        null,
        7.3),
       ('Despicable Me 3',
        null,
        89,
        2017,
        'https://www.imdb.com/title/tt3469046/?ref_=fn_al_tt_1',
        'https://www.youtube.com/watch?v=6DBi41reeF0',
        'https://m.media-amazon.com/images/M/MV5BNjUyNzQ2MTg3Ml5BMl5BanBnXkFtZTgwNzE4NDM3MTI@._V1_.jpg',
        true,
        null,
        6.2),
       ('Guardians of the Galaxy',
        null,
        121,
        2014,
        'Guardians of the Galaxy',
        'https://www.youtube.com/watch?v=d96cjJhvlMA',
        'https://m.media-amazon.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_.jpg',
        true,
        null,
        8.0),
       ('Guardians of the Galaxy Vol. 2',
        null,
        136,
        2017,
        'https://www.imdb.com/title/tt3896198/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=dW1BIid8Osg',
        'https://www.tvguide.com/a/img/catalog/provider/1/2/1-5164672802.jpg',
        true,
        null,
        7.6),
       ('Alice Through the Looking Glass',
        null,
        113,
        2016,
        'https://www.imdb.com/title/tt2567026/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=x3IWwnNe5mc',
        'https://m.media-amazon.com/images/M/MV5BMTc2NjExMTIyN15BMl5BanBnXkFtZTgwMjg0OTIwODE@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        6.1),
       ('Alice in Wonderland',
        null,
        108,
        2010,
        'https://www.imdb.com/title/tt1014759/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=9POCgSRVvf0',
        'https://m.media-amazon.com/images/M/MV5BMTMwNjAxMTc0Nl5BMl5BanBnXkFtZTcwODc3ODk5Mg@@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        6.4),
       ('Alpha',
        null,
        96,
        2018,
        'https://www.imdb.com/title/tt4244998/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=uIxnTi4GmCo',
        'https://images.moviesanywhere.com/e21a9eae664fc7e8519ff87645a5afb2/051eca31-8254-4de3-a183-54dd4cac741d.jpg',
        true,
        null,
        6.6),
       ('Peppermint',
        null,
        101,
        2018,
        'https://www.imdb.com/title/tt6850820/?ref_=nv_sr_srsg_8',
        'https://www.youtube.com/watch?v=eeBMQpzoEXQ',
        'https://m.media-amazon.com/images/M/MV5BMzY5NjYxNGItMzU5MS00Y2M4LWI0ZDYtZGVhN2Q2ZDY2NTUxXkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg',
        true,
        null,
        6.4),
       ('Jungle Cruise',
        null,
        127,
        2021,
        'https://www.imdb.com/title/tt0870154/?ref_=nv_sr_srsg_2',
        'https://www.youtube.com/watch?v=f_HvoipFcA8',
        'https://m.media-amazon.com/images/M/MV5BNDE1MGRlNTQtZjc4ZC00MTI0LWEwY2MtODk1YTM2NmFmYTNmXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg',
        true,
        null,
        6.6),
       ('Jumanji',
        'Welcome to the Jungle',
        119,
        2017,
        'https://www.imdb.com/title/tt2283362/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=2QKg5SZ_35I',
        'https://www.themoviedb.org/t/p/original/pSgXKPU5h6U89ipF7HBYajvYt7j.jpg',
        true,
        null,
        6.9),
       ('Jumanji',
        'The Next Level',
        123,
        2019,
        'https://www.imdb.com/title/tt7975244/?ref_=nv_sr_srsg_5',
        'https://www.youtube.com/watch?v=rBxcF-r9Ibs',
        'https://i.pinimg.com/originals/b7/2f/e3/b72fe38e099a81b453a41274a9675a2d.jpg',
        true,
        null,
        6.7),
       ('The Da Vinci Code',
        null,
        149,
        2006,
        'https://www.imdb.com/title/tt0382625/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=5sU9MT8829k',
        'https://i.pinimg.com/originals/83/a4/57/83a457c4d8dc4325443c4ce52fffe163.png',
        true,
        null,
        6.6),
       ('Angels & Demons',
        null,
        138,
        2009,
        'https://www.imdb.com/title/tt0808151/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=GPaAwbveFLg',
        'https://m.media-amazon.com/images/M/MV5BMjEzNzM2MjgxMF5BMl5BanBnXkFtZTcwNTQ1MTM0Mg@@._V1_.jpg',
        true,
        null,
        6.7),
       ('Ant-Man',
        null,
        117,
        2015,
        'https://www.imdb.com/title/tt0478970/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=pWdKf3MneyI',
        'https://m.media-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        7.3),
       ('Ant-Man and the Wasp',
        null,
        118,
        2018,
        'https://www.imdb.com/title/tt5095030/?ref_=nv_sr_srsg_6',
        'https://www.youtube.com/watch?v=UUkn-enk2RU',
        'https://m.media-amazon.com/images/M/MV5BYjcyYTk0N2YtMzc4ZC00Y2E0LWFkNDgtNjE1MzZmMGE1YjY1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
        true,
        null,
        7.0),
       ('G.I. Joe',
        'The Rise of Cobra',
        118,
        2009,
        'https://www.imdb.com/title/tt1046173/?ref_=nv_sr_srsg_6',
        'https://www.youtube.com/watch?v=lDVvFUbnqEM',
        'https://m.media-amazon.com/images/M/MV5BMTQzMTU1NzQwNl5BMl5BanBnXkFtZTcwNDg4NzMzMw@@._V1_.jpg',
        true,
        null,
        5.7),
       ('G.I. Joe',
        'Retaliation',
        110,
        2013,
        'https://www.imdb.com/title/tt1583421/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=bd3JmlIxQXM',
        'https://i.pinimg.com/originals/3a/63/6d/3a636d389eb156dd58277b26468c32a6.jpg',
        true,
        null,
        5.7),
       ('American Made',
        null,
        115,
        2017,
        'https://www.imdb.com/title/tt3532216/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=AEBIJRAkujM',
        'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/a0837c64030443.5ac4c6f265693.jpg',
        true,
        null,
        7.1),
       ('Daddy''s Home',
        null,
        96,
        2015,
        'https://www.imdb.com/title/tt1528854/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=OeknNwE4e1E',
        'https://i.pinimg.com/originals/90/cc/f2/90ccf2afea694bc85363eb454a3c9928.jpg',
        true,
        null,
        6.1),
       ('Daddy''s Home 2',
        null,
        100,
        2017,
        'https://www.imdb.com/title/tt5657846/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=yyW_EX7iRW0',
        'https://m.media-amazon.com/images/M/MV5BMDU5OWUwMDMtODEyMS00YmU5LWIxYzMtMjUwZGE2MmM0YTkyXkEyXkFqcGdeQXVyMTExODYyNA@@._V1_.jpg',
        true,
        null,
        6.0),
       ('RED',
        null,
        111,
        2010,
        'https://www.imdb.com/title/tt1245526/',
        'https://www.youtube.com/watch?v=-JZ_moituIo',
        'https://m.media-amazon.com/images/M/MV5BMzg2Mjg1OTk0NF5BMl5BanBnXkFtZTcwMjQ4MTA3Mw@@._V1_.jpg',
        true,
        null,
        7.0),
       ('RED 2',
        null,
        116,
        2013,
        'https://www.imdb.com/title/tt1821694/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=ZfB8QwYBPxY',
        'https://www.heyuguys.com/?attachment_id=186321',
        true,
        null,
        6.6),
       ('White House Down',
        null,
        131,
        2013,
        'https://www.imdb.com/title/tt2334879/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=WfaTlmYvTA8',
        'https://m.media-amazon.com/images/M/MV5BYmI5ZGIxOGMtMjcwMS00Yzk3LWE0YWUtMzc5YTFhNGQ4OWZmXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg',
        true,
        null,
        6.3),
       ('Battleship',
        null,
        131,
        2012,
        'https://www.imdb.com/title/tt1440129/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=8NNQqHsIc-4',
        'https://m.media-amazon.com/images/M/MV5BMjI5NTM5MDA2N15BMl5BanBnXkFtZTcwNjkwMzQxNw@@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        5.8),
       ('Bohemian Rhapsody',
        null,
        134,
        2018,
        'https://www.imdb.com/title/tt1727824/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=mP0VHJYFOAU',
        'https://m.media-amazon.com/images/M/MV5BMTA2NDc3Njg5NDVeQTJeQWpwZ15BbWU4MDc1NDcxNTUz._V1_.jpg',
        true,
        null,
        7.9),
       ('Valerian and the City of a Thousand Planets',
        null,
        136,
        2017,
        'https://www.imdb.com/title/tt2239822/?ref_=nv_sr_srsg_10',
        'https://www.youtube.com/watch?v=cPeqNTqZNN0',
        'https://m.media-amazon.com/images/M/MV5BMTkxMDAxNDUyNV5BMl5BanBnXkFtZTgwOTc3MzcxMjI@._V1_.jpg',
        true,
        null,
        6.4),
       ('21 Jump Street',
        null,
        109,
        2012,
        'https://www.imdb.com/title/tt1232829/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=RLoKtb4c4W0',
        'https://www.themoviedb.org/t/p/original/tSK5P9yPzXmFvYrfl36unVDIZ0P.jpg',
        true,
        null,
        7.2),
       ('22 Jump Street',
        null,
        112,
        2014,
        'https://www.imdb.com/title/tt2294449/?ref_=nv_sr_srsg_6',
        'https://www.youtube.com/watch?v=qP755JkDxyM',
        'https://m.media-amazon.com/images/M/MV5BMTcwNzAxMDU1M15BMl5BanBnXkFtZTgwNDE2NTU1MTE@._V1_.jpg',
        true,
        null,
        7.0),
       ('Warrior',
        null,
        140,
        2011,
        'https://www.imdb.com/title/tt1291584/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=I5kzcwcQA1Q',
        'https://m.media-amazon.com/images/M/MV5BMTk4ODk5MTMyNV5BMl5BanBnXkFtZTcwMDMyNTg0Ng@@._V1_.jpg',
        true,
        null,
        8.2),
       ('Never Back Down',
        null,
        113,
        2008,
        'https://www.imdb.com/title/tt1023111/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=ZfB8QwYBPxY',
        'https://i.pinimg.com/originals/9f/85/51/9f85512c0c986addf5c054040b7a4ec6.jpg',
        true,
        null,
        6.5),
       ('Jack Reacher',
        null,
        130,
        2012,
        'https://www.imdb.com/title/tt0790724/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=Q-oxhxD32MM',
        'https://m.media-amazon.com/images/M/MV5BMTM1NjUxMDI3OV5BMl5BanBnXkFtZTcwNjg1ODM3OA@@._V1_.jpg',
        true,
        null,
        7.0),
       ('Jack the Giant Slayer',
        null,
        114,
        2013,
        'https://www.imdb.com/title/tt1351685/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=ng9rjC8MOgU',
        'https://m.media-amazon.com/images/M/MV5BMjE1NDMxMjI0OV5BMl5BanBnXkFtZTcwMjQyMDExOQ@@._V1_.jpg',
        true,
        null,
        6.3),
       ('Dracula Untold',
        null,
        92,
        2014,
        'https://www.imdb.com/title/tt0829150/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=_2aWqecTTuE',
        'https://m.media-amazon.com/images/M/MV5BMTkzNzI1OTI4N15BMl5BanBnXkFtZTgwNTQ2NzEwMjE@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        6.2),
       ('Divergent',
        null,
        139,
        2014,
        'https://www.imdb.com/title/tt1840309/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=sutgWjz10sM',
        'https://i.pinimg.com/736x/85/6e/a3/856ea3ce1634a1610f6919e1cc3cb320.jpg',
        true,
        null,
        6.6),
       ('The Divergent Series',
        'Insurgent',
        119,
        2015,
        'https://www.imdb.com/title/tt2908446/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=IR-l_TSjlEo',
        'https://m.media-amazon.com/images/M/MV5BMTgxOTYxMTg3OF5BMl5BanBnXkFtZTgwMDgyMzA2NDE@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        6.2),
       ('The Divergent',
        'Allegiant',
        120,
        2016,
        'https://www.imdb.com/title/tt3410834/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=tE8LEPSTK6A',
        'https://www.themoviedb.org/t/p/original/etGXQzt6Znfkd5DcqCfGlyWrfxp.jpg',
        true,
        null,
        5.6),
       ('Real Steel',
        null,
        127,
        2011,
        'https://www.imdb.com/title/tt0433035/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=T75j9CoBVzE',
        'https://i.pinimg.com/originals/bf/3c/ec/bf3cec3f82b0c49d11cebc039692f039.jpg',
        true,
        null,
        7.0),
       ('The Equalizer',
        null,
        132,
        2014,
        'https://www.imdb.com/title/tt0455944/?ref_=nv_sr_srsg_3',
        'https://www.youtube.com/watch?v=VjctHUEmutw',
        'https://m.media-amazon.com/images/M/MV5BMTQ2MzE2NTk0NF5BMl5BanBnXkFtZTgwOTM3NTk1MjE@._V1_.jpg',
        true,
        null,
        7.2),
       ('The Equalizer 2',
        null,
        121,
        2018,
        'https://www.imdb.com/title/tt3766354/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=HyNJ3UrGk_I',
        'https://m.media-amazon.com/images/M/MV5BMTU2OTYzODQyMF5BMl5BanBnXkFtZTgwNjU3Njk5NTM@._V1_FMjpg_UX1000_.jpg',
        true,
        null,
        6.7),
       ('RED 2',
        null,
        116,
        2013,
        'https://www.imdb.com/title/tt1821694/?ref_=nv_sr_srsg_0',
        'https://www.youtube.com/watch?v=ZfB8QwYBPxY',
        'https://www.heyuguys.com/?attachment_id=186321',
        true,
        null,
        6.6);

INSERT INTO movies_genres(movie_entity_id, genres_id)
VALUES (1 , 1),
       (1 , 2),
       (2 , 3),
       (2 , 4),
       (3 , 5),
       (3 , 6),
       (4 , 7),
       (4 , 8),
       (5 , 9),
       (5 , 10),
       (6 , 10),
       (7 , 9),
       (7 , 8),
       (7 , 7),
       (8 , 6),
       (8 , 5),
       (9 , 4),
       (9 , 3),
       (10 , 2),
       (10 , 1),
       (11 , 2),
       (11 , 3),
       (12 , 4),
       (13 , 5),
       (13 , 6),
       (14 , 7),
       (15 , 8),
       (16 , 9),
       (17 , 10),
       (18 , 9),
       (19 , 8),
       (20 , 7),
       (21 , 8),
       (22 , 9),
       (23 , 8),
       (24 , 8),
       (25 , 8),
       (26 , 8),
       (27 , 8),
       (28 , 8),
       (29 , 8),
       (30 , 8),
       (31 , 8),
       (32 , 8),
       (33 , 8),
       (34 , 8),
       (35 , 8),
       (36 , 8),
       (37 , 8),
       (38 , 8),
       (39 , 8),
       (40 , 8),
       (41 , 8),
       (42 , 8),
       (43 , 8),
       (44 , 8),
       (45 , 8),
       (46 , 8),
       (47 , 8),
       (48 , 8),
       (49 , 8),
       (50 , 8),
       (51 , 8),
       (52 , 8),
       (53 , 8),
       (54 , 8),
       (55 , 8),
       (56 , 8),
       (57 , 8),
       (58 , 8),
       (59 , 8),
       (60 , 8),
       (61 , 8),
       (62 , 8),
       (63 , 8),
       (64 , 8),
       (65 , 8),
       (66 , 8),
       (67 , 8),
       (68 , 8),
       (69 , 8),
       (70 , 8),
       (71 , 8),
       (72 , 8),
       (73 , 8),
       (74 , 8),
       (75 , 8),
       (76 , 8),
       (77 , 8),
       (78 , 8),
       (80 , 8),
       (81 , 8),
       (82 , 8),
       (83 , 8),
       (84 , 8),
       (85 , 8),
       (86 , 8),
       (87 , 8),
       (88 , 8),
       (89 , 8),
       (90 , 8),
       (91 , 8),
       (92 , 8),
       (93 , 8),
       (94 , 8),
       (95 , 8),
       (96 , 8),
       (97 , 8),
       (98 , 8),
       (99 , 8),
       (100 , 8),
       (101 , 8),
       (102 , 8),
       (103 , 8),
       (104 , 8),
       (105 , 8),
       (106 , 8),
       (107 , 8),
       (108 , 8),
       (109 , 8),
       (110 , 8),
       (111 , 8),
       (112 , 8),
       (113 , 8),
       (114 , 8),
       (115 , 8),
       (116 , 8),
       (117 , 8),
       (118 , 8),
       (119 , 8),
       (120 , 8),
       (121 , 8),
       (122 , 8),
       (123 , 8),
       (124 , 8),
       (125 , 8),
       (126 , 8),
       (127 , 8),
       (128 , 8),
       (129 , 8),
       (130 , 8),
       (131 , 8),
       (132 , 8),
       (133 , 8),
       (134 , 8),
       (135 , 8),
       (136 , 8),
       (137 , 8),
       (138 , 8),
       (139 , 8),
       (140 , 8),
       (141 , 8),
       (142 , 8),
       (143 , 8),
       (144 , 8),
       (145 , 8),
       (146 , 8),
       (147 , 8),
       (148 , 8),
       (149 , 8),
       (150 , 8),
       (151 , 8),
       (152 , 8),
       (153 , 8),
       (154 , 8),
       (155 , 8),
       (156 , 8),
       (157 , 8),
       (158 , 8),
       (159 , 8),
       (160 , 8),
       (161 , 8),
       (162 , 8),
       (163 , 8),
       (164 , 8),
       (165 , 8),
       (166 , 8),
       (167 , 8),
       (168 , 8),
       (169 , 8),
       (170 , 8),
       (171 , 8),
       (172 , 8),
       (173 , 8),
       (174 , 8),
       (175 , 8),
       (176 , 8),
       (177 , 8),
       (178 , 8),
       (179 , 8);


INSERT INTO movies_platforms(movie_entity_id, platforms_id)
VALUES (1 , 1),
       (2 , 2),
       (3 , 3),
       (3 , 2),
       (4 , 3),
       (4 , 1),
       (5 , 2),
       (6 , 3),
       (7 , 2),
       (8 , 1),
       (9 , 2),
       (10 , 1),
       (11 , 3),
       (12 , 2),
       (13 , 1),
       (14 , 2),
       (15 , 3),
       (16 , 2),
       (17 , 1),
       (18 , 2),
       (18 , 3),
       (19 , 2),
       (20 , 1);