export const Constants = {
    error: {
        TITLE1_REQUIRED: 'Title is required and cannot be empty string!',
        TITLE1_LENGTH: 'Title length must be between 2 and 40 characters!',
        TITLE2_LENGTH: 'Second title length must be between 2 and 40 characters!',
        DURATION_REQUIRED: 'Field Duration is required!',
        DURATION_NUMERIC: 'Field Duration must be contains only digits!',
        DURATION_BETWEEN: 'The value of the Duration field must be between 30 and 300 min!',
        YEAR_REQUIRED: 'Field Year is required!',
        YEAR_NUMERIC: 'Field Year must be contains only digits!',
        YEAR_BETWEEN: 'The value of the Year field must be between 1950 and 2100!',
        GENRES_REQUIRED: 'Field Genres is required!',
        GENRES_MAX_LENGTH: 'You can select up to 4 genres!',
        PLATFORMS_REQUIRED: 'Field Platforms is required!',
        PLATFORMS_MAX_LENGTH: 'You can select up to 4 platforms!',
        IMDB_URL: 'The value on IBDbURL field is not valid URL!',
        IMDB_URL_MAX_LENGTH: 'The length of the IMDbURL field must be max 254 characters!',
        POSTER_URL_REQUIRED: 'PosterURL is required and cannot be empty string!',
        POSTER_URL: 'The value on PosterURL field is not valid URL!',
        POSTER_URL_MAX_LENGTH: 'The length of the PosterURL field must be max 254 characters!',
        TRAILER_URL_REQUIRED: 'TrailerURL is required and cannot be empty string!',
        TRAILER_URL: 'The value on TrailerURL field is not valid URL!',
        TRAILER_URL_MAX_LENGTH: 'The length of the TrailerURL field must be max 254 characters!',
        DESCRIPTION_MAX_LENGTH: 'The length of the Description field must be max 254 characters!',
        LANGUAGE_REQUIRED: 'Language is required!',
        USERNAME_REQUIRED: 'Username is required!',
        USERNAME_BETWEEN: 'Username must be between 6 and 10 symbols!',
        USERNAME_ALPHA_NUM: 'Username may contain alpha-numeric characters!',
        PASSWORD_REQUIRED: 'Password is required!',
        PASSWORD_BETWEEN: 'Password must be between 6 and 10 symbols!',
        PASSWORD_ALPHA_NUM: 'Password may contain alpha-numeric characters!',
        CONFIRM_PASSWORD: 'Passwords must be the same!'
    }
}